#!/usr/bin/env python

import gdata.docs.service
import argparse

parser = argparse.ArgumentParser(description='Synchronize pictures with Picsa.')
parser.add_argument('userid', type=str)
parser.add_argument('password', type=str)
args = parser.parse_args()
print "User: %s, Password: %s" % (args.userid, args.password)

# Create a client class which will make HTTP requests with Google Docs server.
client = gdata.docs.service.DocsService()
# Authenticate using your Google Docs email address and password.
client.ClientLogin(args.userid, args.password)

# Query the server for an Atom feed containing a list of your documents.
documents_feed = client.GetDocumentListFeed()
# Loop through the feed and extract each document entry.
for document_entry in documents_feed.entry:
  # Display the title of the document on the command line.
  print document_entry.title.text
